// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Kritikos.NoviSample.Persistence.Migrations
{
    public partial class AddIpToDetailsTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Ip",
                table: "IpDetails",
                nullable: false,
                defaultValue: "");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Ip",
                table: "IpDetails");
        }
    }
}
